name: Deploy staging

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
          echo loc
          curl --location --request GET 'https://appsmith.staging-green.manabie.io/api/v1/git/pull/app/635f52aab3ce396b06d52dbc' \
          --header 'Accept: application/json, text/plain, */*' \
          --header 'branchName: master' \
          --header 'Authorization: Basic YXBwc21pdGhAbWFuYWJpZS5jb206TUBuYWJpZTEyMw=='