name: Deploy staging

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Pull Metadata
      id: pull-metadata
      run: |
          curl --location --request GET 'https://appsmith.staging-green.manabie.io/api/v1/git/pull/app/6360798db3ce396b06d52e39' \
          --header 'Accept: application/json, text/plain, */*' \
          --header 'branchName: master' \
          --header 'Authorization: Basic YXBwc21pdGhAbWFuYWJpZS5jb206TUBuYWJpZTEyMw==' -o pull.json
    
    - name: Read Response
      id: read-reponse 
      run: echo $(cat pull.json)

    - name: Check Response
      id: check-response
      run: |
          v=$(echo $(cat pull.json) | jq '.responseMeta.status')
          echo "${v}"
          if [[ "${v}" == "200"]]; then
            echo "ok"
          else
            echo "fail"
          fi
