name: Deploy staging

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
          echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV
          curl https://example.lab >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
    
          echo "{name}={value}" >> $GITHUB_OUTPUT
