name: Deploy staging

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
          curl --location --request GET 'https://appsmith.local-green.manabie.io:31600/api/v1/git/pull/app/635a42eddc1d1b603e048648' \
          --header 'Accept: application/json, text/plain, */*' \
          --header 'branchName: master' \
          --header 'Authorization: Basic YXBwc21pdGhAbWFuYWJpZS5jb206dGhhbmhsb2M5Mw=='