name: Deploy staging

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
          CODE=`curl --write-out '%{http_code}' --location --request GET 'https://appsmith.staging-green.manabie.io/api/v1/git/pull/app/6360798db3ce396b06d52e39' \
          --header 'Accept: application/json, text/plain, */*' \
          --header 'branchName: master' \
          --header 'Authorization: Basic YXBwc21pdGhAbWFuYWJpZS5jb206TUBuYWJpZTEyMw=='`
          if [ $CODE!="200" ] 
          then
              echo "FAILURE"
          else
              echo "SUCCESS"
          fi
          